version: '3.3'
services:
  mysql:
    image: ahsan0786/proyecto_mysql
    ports:
      - 3306:3306
    networks:
      - db
    volumes:
      - /home/ubuntu/docker/containers/mysql:/var/lib/mysql
      - /home/ubuntu/docker/containers/mysql-config/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: Ausias123@@
  wordpress:
    image: ahsan0786/proyecto_wordpress
    networks:
      - proxy
      - db
    ports:
      - 80:80
    volumes:
      - /home/ubuntu/docker/containers/wordpress:/var/www/html
    environment:
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: Ausias123@@
       WORDPRESS_DB_NAME: wordpress
    deploy:
      replicas: 4
      labels:
       - "traefik.port=80"
       - "traefik.backend.loadbalancer.sticky=true"
#      - "traefik.backend=192.168.0.18,192.168.0.10"
       - "traefik.frontend.rule=Host:webservices.com"
       - "traefik.enable=true"
       - "traefik.docker.network=proxy"
      restart_policy:
        condition: on-failure
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      labels:
       - "traefik.frontend.rule=Host:portainer.webservices.com"
       - "traefik.docker.network=proxy"
       - "traefik.port=9000"
       - "traefik.enable=true"
      placement:
        constraints: [node.role == manager]
networks:
  proxy:
    external: true
  db:
    driver: overlay
