version: '3.3'

networks:
  proxy:
    external: true

services:
  jenkins:
    image: istresearch/jenkins:latest
    user: jenkins
    volumes:
    - /home/ubuntu/docker/containers/jenkins/jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
   #- /home/ubuntu/docker/containers/jenkins/timezone:/etc/timezone
  #- /home/ubuntu/docker/containers/jenkins/localtime:/etc/localtime
    environment:
     JENKINS_HOST_HOME: "/data/jenkins"
    ports:
    - "8082:8080"
    - "5000:5000"
    - "50000:50000"
    networks:
    - proxy
    deploy:
      replicas: 2
      labels:
#       - "traefik.frontend.rule=PathPrefixStrip:/jen"
       - "traefik.frontend.rule=Host:jenkins.docker4all.com"
       - "traefik.docker.network=proxy"
       - "traefik.port=8080"
       - "traefik.enable=true"
  dnsmasq:
    image: jpillora/dnsmasq
    environment:
     HTTP_USER: ausias
     HTTP_PASS: Ausias123@@
    volumes:
     - /home/ubuntu/docker/containers/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
    - 53:53/udp
    - 5380:8080
    networks:	
    - proxy
    deploy:
      replicas: 2
      labels:
#       - "traefik.frontend.rule=PathPrefixStrip:/dns"
       - "traefik.frontend.rule=Host:dns.docker4all.com"
       - "traefik.docker.network=proxy"
       - "traefik.port=8080"
       - "traefik.enable=true"
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      labels:
       - "traefik.frontend.rule=Host:portainer.docker4all.com"
       - "traefik.docker.network=proxy"
       - "traefik.port=9000"
       - "traefik.enable=true"
      placement:
        constraints: [node.role == manager] 
